version: '3.9'

services:
  cqu-net:
    image: ghcr.io/skyswordw/cqu-net:latest
    container_name: cqu-net
    restart: always
    environment:
      - ACCOUNT=你的学号或工号         # 必需：例如 20221401013
      - PASSWORD=你的密码              # 必需：例如 123456
      - TERM_TYPE=pc                 # 可选：登录设备类型 (pc 或 android)，默认 pc
      - LOG_LEVEL=info               # 可选：日志级别 (info 或 debug)，默认 info
      - INTERVAL=5                   # 可选：检测间隔时间（秒），默认 5秒